openapi: 3.0.3
info:
  title: User & Follow API
  version: 1.0.0
  description: |
    API pre správu používateľov, fotiek, sledovania a komentárov.
servers:
  - url: http://localhost:3000/api
tags:
  - name: Guest
  - name: User
  - name: Follow
  - name: Photo
  - name: Comments
security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        fname:
          type: string
        lname:
          type: string
        avatar:
          type: string
          nullable: true
        followers:
          type: integer
        following:
          type: integer
        photos:
          type: array
          items:
            $ref: "#/components/schemas/PhotoResponse"

    PhotoResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        filename:
          type: string
        url:
          type: string
        createdAt:
          type: string
          format: date-time
        photoTags:
          type: array
          items:
            $ref: "#/components/schemas/TagResponse"

    TagResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string

    TokenResponse:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

    CommentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        text:
          type: string
        createdAt:
          type: string
          format: date-time
        user:
          $ref: "#/components/schemas/CommentUser"
        photoId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid

    CommentUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        fname:
          type: string
        lname:
          type: string
        avatar:
          type: string
          nullable: true

    CommentRequest:
      type: object
      required:
        - photoId
        - text
      properties:
        photoId:
          type: string
          format: uuid
        text:
          type: string

    CommentsListResponse:
      type: object
      properties:
        comments:
          type: array
          items:
            $ref: "#/components/schemas/CommentResponse"

    SuccessResponse:
      type: object
      properties:
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        message:
          type: string

paths:
  /sign-up:
    post:
      summary: Register new user
      tags: [Guest]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: Username already taken or invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /sign-in:
    post:
      summary: Login user
      tags: [Guest]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: JWT token returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "401":
          description: Wrong credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /protected:
    get:
      summary: Test protected route
      tags: [User]
      security: [{ bearerAuth: [] }]
      responses:
        "200":
          description: Authorized user info
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: string
                  username:
                    type: string
        "401":
          description: Invalid or missing token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /get-user:
    get:
      summary: Get current logged-in user data
      tags: [User]
      security: [{ bearerAuth: [] }]
      responses:
        "200":
          description: Full user info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /update-avatar:
    post:
      summary: Update user avatar
      tags: [User]
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [avatar]
              properties:
                avatar:
                  type: string
                  description: Base64 or image URL
      responses:
        "200":
          description: Avatar updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  avatar:
                    type: string
        "400":
          description: Missing or invalid avatar data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /upload-photo:
    post:
      summary: Upload a new photo
      tags: [Photo]
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [photo]
              properties:
                photo:
                  type: string
                  format: binary
                tags:
                  type: string
                  description: Space-separated tags (e.g. "beach sunset travel")
      responses:
        "201":
          description: Photo uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  photo:
                    $ref: "#/components/schemas/PhotoResponse"
        "400":
          description: No file uploaded or invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /photo/{id}:
    delete:
      summary: Delete photo by ID
      tags: [Photo]
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Photo deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "403":
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Photo not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /search-users:
    get:
      summary: Search for users
      tags: [User]
      security: [{ bearerAuth: [] }]
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
      responses:
        "200":
          description: List of found users
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/UserResponse"

  /user/{username}:
    get:
      summary: Get user by username
      tags: [User]
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
      responses:
        "200":
          description: User profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /follow:
    post:
      summary: Follow user
      tags: [Follow]
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId]
              properties:
                userId:
                  type: string
                  format: uuid
      responses:
        "200":
          description: Followed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  followers:
                    type: integer
                  following:
                    type: integer
                  isFollowing:
                    type: boolean
        "400":
          description: Already following or invalid user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /unfollow:
    post:
      summary: Unfollow user
      tags: [Follow]
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId]
              properties:
                userId:
                  type: string
                  format: uuid
      responses:
        "200":
          description: Unfollowed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  followers:
                    type: integer
                  following:
                    type: integer
                  isFollowing:
                    type: boolean
        "400":
          description: You do not follow this user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /followers/{userId}:
    get:
      summary: Get followers of user
      tags: [Follow]
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: userId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Followers list
          content:
            application/json:
              schema:
                type: object
                properties:
                  followers:
                    type: array
                    items:
                      $ref: "#/components/schemas/UserResponse"

  /following/{userId}:
    get:
      summary: Get following of user
      tags: [Follow]
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: userId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Following list
          content:
            application/json:
              schema:
                type: object
                properties:
                  following:
                    type: array
                    items:
                      $ref: "#/components/schemas/UserResponse"

  /follow-status/{userId}:
    get:
      summary: Check follow status
      tags: [Follow]
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: userId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Follow status
          content:
            application/json:
              schema:
                type: object
                properties:
                  isFollowing:
                    type: boolean

  # ===== COMMENT ENDPOINTS =====
  /photo/{photoId}/comments:
    get:
      summary: Get comments for a photo
      tags: [Comments]
      security: [{ bearerAuth: [] }]
      parameters:
        - name: photoId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '200':
          description: Successfully retrieved comments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentsListResponse'
        '400':
          description: Invalid photo ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Photo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /comment:
    post:
      summary: Add a new comment
      tags: [Comments]
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
      responses:
        '201':
          description: Comment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentResponse'
        '400':
          description: Invalid input or missing required fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Photo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /comment/{commentId}:
    delete:
      summary: Delete a comment
      tags: [Comments]
      security: [{ bearerAuth: [] }]
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '200':
          description: Comment deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - not authorized to delete this comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Comment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'